### ISSUE TITLE
Template Gallery Feedback

### ISSUE THREAD

**Issue by delsonting** [DerbySoft/derbysoft-gtm-template#1]
Your template has been approved and should be live in the Template Gallery shortly. A question about your template.tpl file, you require sendPixel however the code does not appear to make use of this function. I would recommend you not require sendPixel if it's not used in the code.

**Comment by joe-you-derbysoft** [comment]
Thanks delson. 
I want to transfer my template to corp, so i create a new one.
https://github.com/derbysoft/gtm-template-metatag

how can i do, please give me some advice.
Our client has malware warning, so i need switch to gtm tamplate. Thank you.
